export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_USER = "RETRIEVE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PRODUCT = "RETRIEVE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const RETRIEVE_ALL_PRODUCTS = "RETRIEVE_ALL_PRODUCTS";
export const FIND_PRODUCTS_BY_NAME = "FIND_PRODUCTS_BY_NAME";
